#Copy all sequence summaries generated by guppy into the minionQC folder and run the script below

#!/bin/bash
#SBATCH --partition normal
#SBATCH --mem-per-cpu 16G
#SBATCH -c 12
#SBATCH -t 12:00:00

Rscript /home/samirwatson/MinionQC/Minion_R_QC_Script/MinIONQC.R -i /home/samirwatson/faststorage/METTL3/DRS_data/QC/minionQC \
-p 12 \
-s TRUE \
-f 'pdf'
